# Site settings
title:       Jorin's Tech Logbook - Collecting Thoughts For No Reason
author:      Jorin
description: "Weird ideas and unimportant observations should be kept somewhere!"
url:         https://jorin.me

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      categories: lab


layout:     post
categories: lab

disqus_shortname: jorinvo
github_username: jorinvo
twitter_username: jorinvo

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:title
paginate:     10
sass:
  compressed: true
exclude: ['vendor', 'Gemfile', 'Gemfile.lock']
