# Site settings
title:       Jorin's Tech Logbook - Collecting Thoughts For No Reason
author:      Jorin
description: "Weird ideas and unimportant observations should be kept somewhere!"
url:         https://jorin.me

disqus_shortname: jorinvo
github_username: jorinvo
twitter_username: jorinvo


defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      categories: lab


layout: post

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:title/
paginate: 10
sass:
  style: :compressed
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
