title: Jorin's Logbook
baseurl: https://jorin.me/
languageCode: en-us
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
enableRobotsTXT: true

author:
  name: Jorin Vogel

permalinks:
  post: /:filename/

params:
  description: Writings about language, text interfaces, taming computers, testing and more things
  email: hi@jorin.me
  github: jorinvo
  twitter: jorinvo
  disqus: jorinvo

pygmentsuseclasses: true
pygmentscodefences: true
